### ISSUE TITLE
Substitute the English Keyboard Layout with Hangul

### ISSUE THREAD

**Issue by Jiali-Xing** [oniondelta/Hangul_Rime_Files#1]
Hi, I really appreciate the Hangul2set configuration for Rime input method.

I wonder if it is possible to replace the English Keyboard with Hangul. As when I use this input method on Android, it has a English keyboard layout displayed (i.e., on my phone if I type `z`, it become `ㅋ`), whereas I want it to display `ㅋ` on the keyboard by itself.

Is it possible to change the display of keyboard to Hangul (for mobile usage). I attached the comparison of Cangjie and Hangul2set to show my point:

![photo_2020-12-19_16-37-18](https://user-images.githubusercontent.com/53011060/102700131-b1037280-4242-11eb-95d0-d1b6a480d857.jpg)
![photo_2020-12-19_16-37-17](https://user-images.githubusercontent.com/53011060/102700133-b2cd3600-4242-11eb-89d5-eeabf079902b.jpg)

**Comment by oniondelta** [comment]
Yes, it's possible to change the display of keyboard to Hangul (for mobile usage)

You can add to a code {label: 'ㅋ'} in any key that you want to replace.

refer to:

https://github.com/oniondelta/Onion_Trime_Files/blob/master/trimefiles/%E6%B4%8B%E8%94%A5%E6%B3%A8%E9%9F%B3_M.trime.yaml

and below

preset_keyboards:

paste the following :


  hangeul2set:
    author: "洋蔥"
    name: 26鍵hangeul2set佈局
    width: 10
  #  height: 48
    height: *jpgd10
    ascii_mode: 0
    lock: true
    keys:
      - {label: 'ㅂ', click: q, long_click: 1, key_back_color: bh1, key_text_color: th1}
      - {label: 'ㅈ', click: w, long_click: 2, key_back_color: bh1, key_text_color: th1}
      - {label: 'ㄷ', click: e, long_click: 3, key_back_color: bh1, key_text_color: th1}
      - {label: 'ㄱ', click: r, long_click: 4, key_back_color: bh1, key_text_color: th1}
      - {label: 'ㅅ', click: t, long_click: 5, key_back_color: bh1, key_text_color: th1}
      - {label: 'ㅛ', click: y, long_click: 6, key_back_color: bh1, key_text_color: th1}
      - {label: 'ㅕ', click: u, long_click: 7, key_back_color: bh1, key_text_color: th1}
      - {label: 'ㅑ', click: i, long_click: 8, key_back_color: bh1, key_text_color: th1}
      - {label: 'ㅐ', click: o, long_click: 9, key_back_color: bh1, key_text_color: th1}
      - {label: 'ㅔ', click: p, long_click: 0, key_back_color: bh1, key_text_color: th1}

      - {width: 5, key_back_color: bh2, key_text_color: th2}
      - {label: 'ㅁ', click: a, long_click: select_all, key_back_color: bh2, key_text_color: th2}
      - {label: 'ㄴ', click: s, long_click: '@', key_back_color: bh2, key_text_color: th2}
      - {label: 'ㅇ', click: d, long_click: '#', key_back_color: bh2, key_text_color: th2}
      - {label: 'ㄹ', click: f, long_click: '$', key_back_color: bh2, key_text_color: th2}
      - {label: 'ㅎ', click: g, long_click: '%', swipe_down: "date_time", key_back_color: bh2, key_text_color: th2}
      - {label: 'ㅗ', click: h, long_click: '!', swipe_down: "+", key_back_color: bh2, key_text_color: th2}
      - {label: 'ㅓ', click: j, long_click: '&', swipe_down: "-", key_back_color: bh2, key_text_color: th2}
      - {label: 'ㅏ', click: k, long_click: '*', swipe_down: "_", key_back_color: bh2, key_text_color: th2}
      - {label: 'ㅣ', click: l, long_click: '(){Left}', swipe_down: "=", key_back_color: bh2, key_text_color: th2}
      - {width: 5, key_back_color: bh2, key_text_color: th2}

      - {click: Shift_L, composing: delimiter, width: 15, hilited_key_back_color: benter, key_back_color: bbs, key_text_color: tbs}
      - {label: 'ㅋ', click: z, long_click: '`', swipe_down: '[]{Left}', key_back_color: bh3, key_text_color: th3}
      - {label: 'ㅌ', click: x, long_click: cut, swipe_down: '{}{Left}', key_back_color: bh3, key_text_color: th3}
      - {label: 'ㅊ', click: c, long_click: copy, swipe_down: ' ', key_back_color: bh3, key_text_color: th3}
      - {label: 'ㅍ', click: v, long_click: paste, swipe_down: "\\", key_back_color: bh3, key_text_color: th3}
      - {label: 'ㅠ', click: b, long_click: ";", key_back_color: bh3, key_text_color: th3}
      - {label: 'ㅜ', click: n, long_click: ":", key_back_color: bh3, key_text_color: th3}
      - {label: 'ㅡ', click: m, long_click: '?', swipe_down: "|", key_back_color: bh3, key_text_color: th3}
      - {click: BackSpace, width: 15, key_back_color: bbs, key_text_color: tbs}

      - {click: Keyboard_number, long_click: Menu_duse, width: 12.5, key_back_color: bgn, key_text_color: tgn, key_symbol_color: tajs, height: *jpgd9}
      - {click: Keyboard_bqrw, long_click: Theme_settings, width: 12.5, key_back_color: bgn, key_text_color: tgn, key_symbol_color: tajs}
      - {click: ',', label: '，', long_click: '<>{Left}', key_back_color: bh4, key_text_color: th4}
      - {click: space, long_click: Mode_switch, swipe_left: "Left", swipe_right: "Right", swipe_up: Keyboard_kmenu, width: 30, key_back_color: bkg, key_text_color: tkg} #, swipe_up: Schema_switchcn
      - {click: '.', label: '。', long_click: Keyboard_kao, key_back_color: bh4, key_text_color: th4}
      - {click: Return, swipe_up: Escape, width: 25, key_back_color: benter, key_text_color: tenter}

**Comment by oniondelta** [comment]
Yes, it's possible to change the display of keyboard to Hangul (for mobile usage)

You can add to a code {label: 'ㅋ'} in any key that you want to replace.

New keyboard file of trime with Hangul2set：
https://github.com/oniondelta/Hangul_Rime_Files/blob/master/trime/Hangul2set_M.trime.yaml

![image](https://raw.githubusercontent.com/oniondelta/Hangul_Rime_Files/master/trime/Hangul2set_M.jpg)

**Comment by Jiali-Xing** [comment]
That's Terrific! Besides, your `Hangul2set_M.trime.yaml` is generally a great tutorial for customizing `trime` as well. A million thanks!
