### ISSUE TITLE
韓文輸入和他們實際發音似乎有出入？

### ISSUE THREAD

**Issue by laichiaheng** [oniondelta/Hangul_Rime_Files#2]
Google 之後看到「이다혜」在他們的發音是「Lee Da Hye」，但是照表在輸入法實際要打成「Xi Da Hyei」。
光是第一個字就完全不一樣了。

**Comment by oniondelta** [comment]
[README.md](https://github.com/oniondelta/Hangul_Rime_Files/blob/main/README.md) 說明的很清楚
這是 [韓文 HNC 鍵位](https://github.com/oniondelta/Hangul_Rime_Files/blob/main/Hangul_HNC/README.md)
為韓文音碼平均碼長最短的鍵位佈局，
韓文拼音形式有很多種！
說明看一下！Google 爬文一下！
