### ISSUE TITLE
[Not an issue] Potential collaboration with FydeRhythm

### ISSUE THREAD

**Issue by alphato-o** [oniondelta/Hangul_Rime_Files#3]
Greetings! We are the authors of [openFyde](https://github.com/openfyde) and [FydeOS](https://fydeos.io).

Within openFyde and FydeOS, we have created an IME tool based on the RIME engine; we call it FydeRhythm; it's fully open-source, with all the design documentation available at https://github.com/FydeOS/fydeRhythm.

FydeRhythm can [also be used under Google ChromeOS](https://chrome.google.com/webstore/detail/%E7%9C%9F%E6%96%87%E9%9F%B5%E8%BE%93%E5%85%A5%E6%B3%95/ppgpjbgimfloenilfemmcejiiokelkni), providing a nice alternative to the only mediocre native CJK input method available in chromeOS. 

 In the settings page of FydeRhythm, users can select preferred compatible RIME files; we have included links to the original GitHub source for each and every one of the RIME schemes. As of today, we have only made Chinese languages RIME schemes available within FydeRhythm; but we have received many requests to add support for Japanese and Korean.

We appreciate and value your hard work on this Hangul_Rime_Files project; we wish to incorporate your project into FydeRhythm, making your work available to help openFyde, FydeOS, as well as many chromeOS users who wish to input Korean.

We notice that in your project, there is no LICENSE defined, and you have explicitly mentioned that "Commercial use is prohibited". Therefore we have created this "issue" to see if we could have your permission/authorisation to include your RIME files in FydeRhythm, with links to this repository.

Appreciate your response; cheers.

**Comment by oniondelta** [comment]
I agree to include my RIME files in FydeRhythm, with links to this repository.
